### ISSUE TITLE
Add TS map example input dataset

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy-extra#11]
Please add an example dataset that can be used to quickly try  / test / benchmark the TS map computation from https://github.com/gammapy/gammapy/pull/215

**Comment by cdeil** [comment]
Closing this old issue. I think it was resolved in Dec 2014 and we forgot to close the issue.

I'm thinking maybe we should disable the `gammapy-extra` issue tracker and just use the `gammapy` issue tracker because one tracker is simpler / better than several?
@adonath @joleroi - What do you think?

**Comment by adonath** [comment]
:+1:  To close this issue tracker and just add a label `gammapy-extra` in the gammapy issue tracker.
