### ISSUE TITLE
Missing ``dummy_exclusion.fits`` file

### ISSUE THREAD

**Issue by bsipocz** [gammapy/gammapy-extra#23]
The file ``gammapy-extra/test_datasets/spectrum/dummy_exclusion.fits`` is used in ``gammapy`` in several places (a recent addition in 68ea123769a5710018f74dfbb754fcee0d05af99), but wasn't added to ``gammapy-extra``.

I'll xfail test for the time being to avoid the failures.

**Comment by cdeil** [comment]
@joleroi - Can you please take care of this?

**Comment by joleroi** [comment]
This is taken care of in #403

**Comment by cdeil** [comment]
This issue came up again in #419, but I think is now fixed in #420.
@joleroi - Close this gammapy-extra issue once #420 is merged (or now)?
